### PR TITLE
Remove `constraint_power_magnitude_sqr_on_off(pm::_PM.AbstractQCWRModel ...)`

### LINKED ISSUE #73: Precompilation is broken due to `constraint_power_magnitude_sqr_on_off`
the function `_PM.constraint_power_magnitude_sqr_on_off(pm::_PM.AbstractQCWRModel, n::Int, i, f_bus, arc_from, tm)` overwrite the PowerModels function by the same name, breaking precompilation.

However, QC is not currently a supported formulation for these problems, and has no test coverage.  This dead code breaks precompilation for no good reason.

### PR DESCRIPTION
**Pull request by noahrhodes**
Closes #73

### CODE REVIEW

File: src/form/wr.jl [hunk 1]
```diff
@@ -126,29 +126,6 @@ function constraint_voltage_magnitude_bounds_soft(pm::_PM.AbstractWRModel, n::In
...
-    z    = _PM.var(pm, n, :z_branch, i)
-
-    # TODO see if there is a way to leverage relaxation_complex_product_on_off here
-    w_lb, w_ub = InfrastructureModels.variable_domain(w)
-    ccm_lb, ccm_ub = InfrastructureModels.variable_domain(ccm)
-    if isinteger(z)
-        z_lb = z_ub = z
-    else
-        z_lb, z_ub = InfrastructureModels.variable_domain(z)
-    end
```
Comment (Robbybp) [inline src/form/wr.jl:144]: Just noting here, while I remember, that this "if block" is the main difference between this and the PowerModels implementation. If this function is necessary for anything, we should (a) document the purpose of this change and (b) find a way to implement it without redefining the PowerModels method.

Comment (noahrhodes) [reply src/form/wr.jl:144]: This goes back 5 years, but if I remember right, the intent is that only damaged lines have a binary variable.  Non-damaged lines have the non-switching power flow constraints, while damaged lines have the switching power flow constraints.
